/** 28 beauty — photo pool [112..139]. */
export default {
  names: [
    'Refillable Lip Balm',
    'Vegan Mascara Tube',
    'Eco Makeup Brush Set',
    'Reusable Cotton Rounds',
    'Natural Tint Moisturizer',
    'Plastic-Free Face Mask',
    'Mineral Blush Compact',
    'Brow Pomade Pot',
    'Setting Powder Refill',
    'Gel Eyeliner Pencil',
    'Duo Eyeshadow Pan',
    'Nail Buffer Block',
    'Micellar Water Glass',
    'Jojoba Cleansing Oil',
    'Overnight Lip Mask',
    'Konjac Face Sponge',
    'Tinted Brow Gel',
    'Highlighter Stick',
    'Matte Lip Crayon',
    'Makeup Remover Balm',
    'Kabuki Brush Short',
    'Sheer Nail Polish',
    'Cuticle Oil Pen',
    'Face Mist Spray',
    'Biodegradable Glitter Gel',
    'Bamboo Cotton Swabs',
    'SPF Face Stick',
    'Eyeshadow Brush Duo',
  ],
  descriptions: [
    'Tinted lip balm in a refillable aluminum slider.',
    'Mascara built with plant waxes and mineral pigment.',
    'Twelve makeup brushes with bamboo handles and vegan fibers.',
    'Washable cotton rounds for toner and makeup removal.',
    'Tinted moisturizer with non-nano mineral SPF.',
    'Clay face mask powder you mix fresh with water.',
    'Pressed mineral blush in a compact paper sleeve.',
    'Water-resistant brow pomade in a glass jar.',
    'Loose powder refill for your existing magnetic compact.',
    'Gel pencil with smudger tip; sharpener included.',
    'Two complementary shades in a paper palette.',
    'Four-sided buffer for natural nail shine.',
    'Micellar in returnable glass with aluminum cap.',
    'Light oil removes sunscreen and long-wear makeup.',
    'Rich overnight treatment for cracked lips.',
    'Heart-shaped konjac for cheeks and T-zone.',
    'Fibrous gel shapes brows without flaking.',
    'Cream stick highlighter with subtle pearl.',
    'Twist-up crayon with plant waxes.',
    'Solid balm melts away makeup; rinse clean.',
    'Dense kabuki for mineral foundation buffing.',
    'Water-based polish in earth-tone shades.',
    'Brush-on cuticle oil with vitamin E.',
    'Rose hydrosol mist for setting and refresh.',
    'Plant-based glitter for festival looks.',
    'Precision swabs for makeup fixes.',
    'Broad-spectrum stick for nose and ears.',
    'Shader and crease brushes in travel sleeve.',
  ],
  materials: [
    'Castor oil, candelilla wax, refill pod',
    'Plant waxes, iron oxide pigments',
    'Bamboo, synthetic taklon (vegan)',
    'Organic cotton flannel',
    'Zinc oxide, shea butter, jojoba',
    'Kaolin clay, aloe, green tea extract',
    'Mica, jojoba oil, vitamin E',
    'Castor wax, pigments, glass',
    'Mica, rice starch, refill pouch',
    'Plant oils, mineral pigments',
    'Mica, shea, paper compact',
    'Sandpaper grits, recycled paper',
    'Micellar water, glass, aluminum',
    'Simmondsia chinensis oil',
    'Shea, squalane, berry wax',
    'Konjac, charcoal infusion',
    'Cellulose fibers, glycerin',
    'Mica, coconut oil, candelilla',
    'Candelilla, pigments, paper',
    'Sunflower oil, emulsifying wax',
    'Dense synthetic, bamboo handle',
    'Water base, mineral pigments',
    'Jojoba, vitamin E, brush',
    'Rose water, glycerin, glass',
    'Cellulose glitter, aloe base',
    'Bamboo, organic cotton tips',
    'Zinc oxide, shea, paper tube',
    'Synthetic taklon, aluminum ferrule',
  ],
  prices: [
    8.99, 14.99, 18.99, 9.99, 14.99, 11.99, 13.99, 12.49, 16.99, 11.99, 15.99, 6.99, 13.49, 17.99, 9.99, 8.49, 12.99, 14.49,
    10.99, 18.49, 16.99, 9.99, 7.99, 11.49, 12.99, 5.99, 14.99, 13.99,
  ],
};
