export default {
  names: [
    'Organic Cotton Tee',
    'Recycled Denim Jacket',
    'Hemp Blend Hoodie',
    'Linen Everyday Shirt',
    'Recycled Knit Sweater',
    'Bamboo Lounge Pants',
    'Vegan Canvas Sneakers',
    'Recycled Fleece Zip Hoodie',
    'Linen Summer Shorts',
    'Fair Trade Merino Beanie',
    'Cork Strap Sandals',
    'RPET Active Leggings',
    'Tencel Camp Shirt',
    'Upcycled Banner Tote',
    'Organic Crew Socks Pack',
    'Seaqual Swim Shorts',
    'Alpaca Wool Cardigan',
    'Pinatex Waist Belt',
    'Plant Dyed Bandana',
    'GOTS Pajama Set',
    'Ripstop Windbreaker',
    'Cork Sole Slippers',
    'Hemp Market Tote',
    'Tie-Dye Scarf',
    'Recycled Cashmere Wrap',
    'Linen Pinafore Dress',
    'Banner Fabric Windcoat',
    'Bamboo Rib Tank',
  ],
  descriptions: [
    'Soft daily tee in GOTS-certified organic cotton with a relaxed fit.',
    'Classic-fit jacket in denim woven with recycled cotton and polyester.',
    'Midweight hoodie blending organic cotton and hemp for year-round wear.',
    'Breathable shirt in European linen with organic cotton trim.',
    'Cozy sweater spun with recycled fibers to cut virgin wool use.',
    'Loungewear jersey from bamboo viscose blended with organic cotton.',
    'Low-profile sneakers with organic cotton canvas and natural rubber soles.',
    'Warm zip hoodie in recycled polyester fleece with ribbed cuffs.',
    'Lightweight linen shorts with drawcord waist for warm days.',
    'Soft merino beanie from fair-trade wool with minimal itch.',
    'Sandals with cork footbed and adjustable straps.',
    'High-rise leggings from recycled PET with four-way stretch.',
    'Camp collar shirt in Tencel lyocell with corozo buttons.',
    'Tote stitched from upcycled banner fabric with cotton lining.',
    'Three-pack crew socks in organic cotton with reinforced heels.',
    'Swim shorts lined with fabric made from ocean-bound plastic.',
    'Open cardigan in alpaca blend with patch pockets.',
    'Vegan belt from pineapple leaf fiber with brass buckle.',
    'Square bandana dyed with plant extracts; color may vary.',
    'Two-piece pajama set in GOTS cotton with elastic waist.',
    'Packable windbreaker in recycled ripstop with hood.',
    'Indoor slippers with cork sole and wool felt upper.',
    'Large market tote in heavy hemp canvas with long handles.',
    'Lightweight scarf with natural tie-dye pattern.',
    'Soft wrap in recycled cashmere blend for cool evenings.',
    'Pinafore dress in linen blend with side pockets.',
    'Statement coat from upcycled event banners; each piece is unique.',
    'Ribbed tank in bamboo viscose for layering.',
  ],
  materials: [
    '100% GOTS organic cotton jersey',
    'Recycled cotton, recycled polyester denim',
    'Organic cotton, hemp, elastane',
    'European linen, organic cotton trim',
    'Recycled wool blend, recycled acrylic',
    'Bamboo viscose, organic cotton',
    'Organic cotton canvas, natural rubber',
    'Recycled polyester fleece, organic cotton rib',
    'European linen, coconut-button fly',
    'Fair-trade merino wool',
    'Cork, vegetable-tanned leather alternative',
    'Recycled PET, elastane',
    'Tencel lyocell, corozo nut buttons',
    'Upcycled PVC banner, organic cotton lining',
    'GOTS organic cotton, elastane',
    'Recycled ocean plastic blend, mesh liner',
    'Alpaca, recycled nylon',
    'Pinafiber, brass buckle',
    'Organic cotton, plant dyes',
    'GOTS organic cotton twill',
    'Recycled nylon ripstop, DWR finish',
    'Cork, wool felt, natural rubber',
    'Hemp canvas, cotton webbing',
    'Organic cotton, natural dyes',
    'Recycled cashmere, wool',
    'Linen, viscose lining',
    'Upcycled synthetic banner, cotton trim',
    'Bamboo viscose, elastane',
  ],
  prices: [
    18.99, 64.99, 42.99, 34.99, 46.99, 28.99, 54.99, 48.99, 32.99, 22.99, 39.99, 36.99, 44.99, 29.99, 14.99, 49.99, 72.99,
    31.99, 16.99, 58.99, 59.99, 34.99, 24.99, 19.99, 89.99, 52.99, 69.99, 21.99,
  ],
};
