/** 28 food & drink — photo pool [196..223]. */
export default {
  names: [
    'Fair-Trade Organic Coffee',
    'Loose Leaf Herbal Tea',
    'Small-Batch Probiotic Kombucha',
    'Raw Wildflower Honey',
    'Single-Origin Dark Chocolate Bar',
    'Bronze-Cut Organic Durum Pasta',
    'Sprouted Grain Breakfast Granola',
    'Home-Compostable Coffee Pods',
    'Sea Salt Oven-Roasted Nut Mix',
    'Plant Protein Smoothie Blend',
    'Unsweetened Apple Sauce Pouches',
    'Hearty Lentil Vegetable Soup Mix',
    'Ancient Grains and Wild Rice Blend',
    'Sparkling Mineral Water Glass Pack',
    'Cold-Pressed Olive Oil',
    'Organic Maple Syrup Grade A',
    'Stone-Ground Whole Wheat Flour',
    'Coconut Aminos Seasoning',
    'Chia Pudding Mix Vanilla',
    'Roasted Seaweed Snack Pack',
    'Pickled Fermented Vegetables',
    'Almond Butter Crunchy',
    'Herbal Rooibos Chai Bags',
    'Freeze-Dried Berry Mix',
    'Sourdough Bread Mix',
    'Spiced Apple Cider Concentrate',
    'Brown Rice Noodles',
    'Mineral Electrolyte Tablets',
  ],
  descriptions: [
    'Whole-bean arabica coffee roasted medium; sourced from grower cooperatives with transparent farm-gate pricing.',
    'Loose-leaf herbal infusion: caffeine-free botanical blend in a steel caddy—steep three to five minutes in hot water.',
    'Small-batch kombucha: live cultures, light carbonation, and organic cane sugar; sold in returnable glass where the refill program operates.',
    'Raw wildflower honey with minimal filtration; traceable to regional apiaries that prioritize hive health and forage diversity.',
    'Dark chocolate bar with a high-cocoa recipe; cocoa mass and butter from fair-trade certified farms and a short ingredient list.',
    'Bronze-cut organic durum pasta, slow-dried so sauces cling; pantry staple for quick weeknight bowls and bakes.',
    'Sprouted-grain granola: oven-toasted clusters of oats, seeds, and coconut chips with maple sweetness—crunchy, not dusty.',
    'Specialty-grade coffee sealed in home- or industrially compostable pods where local rules allow; check your compost service.',
    'Savory snack mix of almonds, cashews, and peanuts, oven-roasted with sea salt and packed in a paper pouch with plant-based liner.',
    'Vegan protein powder blending pea and rice protein with coconut sugar; stirs smoothly into smoothies and plant milks.',
    'Unsweetened apple sauce in squeeze pouches: apples and a touch of vitamin C only; pouches recyclable via participating drop-off schemes.',
    'Hearty dry soup mix: red lentils, pearl barley, dehydrated vegetables, and spices—simmer twenty-five minutes with water or broth.',
    'Side-dish grain mix of brown rice, wild rice, and red quinoa; rinse, then simmer until tender and fluffy.',
    'Sparkling mineral water from a protected spring, bottled in glass with aluminum caps; variety pack of plain and light natural essences.',
    'Extra-virgin oil from single-estate olives; cold-pressed within hours of harvest.',
    'Dark amber syrup from certified sugar bush; great on oatmeal and baking.',
    'Stone-milled whole wheat for hearty loaves and pancakes.',
    'Soy-free alternative to soy sauce; coconut sap and sea salt.',
    'Add plant milk overnight for ready chia pudding.',
    'Lightly salted nori sheets roasted in batches.',
    'Probiotic-rich kraut and kimchi in glass jars.',
    'Single-ingredient almonds, lightly roasted.',
    'Caffeine-free spiced blend in compostable tea bags.',
    'No sugar added; crunchy snack or cereal topper.',
    'Dry mix with dehydrated starter culture instructions.',
    'Concentrate dilutes into hot spiced cider for gatherings.',
    'Rice and water only; quick-cooking gluten-free noodles.',
    'Dissolve in water after exercise; light citrus flavor.',
  ],
  materials: [
    'Arabica coffee, kraft bag, plant-based liner',
    'Organic herbs, steel tin',
    'Brewed tea, organic cane sugar, live cultures, glass bottle',
    'Raw honey, glass jar, metal lid',
    'Cocoa mass, cocoa butter, coconut sugar',
    'Organic durum wheat semolina',
    'Sprouted oats, sunflower seeds, maple syrup, coconut oil',
    'Bio-based capsule, specialty arabica',
    'Almonds, cashews, peanuts, sea salt',
    'Pea protein, rice protein, coconut sugar, natural flavors',
    'Organic apples, ascorbic acid, recyclable pouch film',
    'Red lentils, pearl barley, dried vegetables, spices, glass jar',
    'Brown rice, wild rice, red quinoa',
    'Natural mineral water, glass, aluminum cap',
    'Organic olives, dark glass bottle',
    'Pure maple syrup, glass',
    'Organic hard red wheat',
    'Coconut sap, sea salt',
    'Chia seeds, coconut sugar, vanilla',
    'Nori, sesame oil, sea salt',
    'Cabbage, chili, garlic, salt, glass',
    'Roasted almonds, glass jar',
    'Rooibos, spices, compostable filter paper',
    'Strawberry, blueberry, raspberry, nothing else',
    'Wheat flour, dehydrated starter, salt',
    'Apple juice concentrate, spices, citric acid',
    'Brown rice flour, water',
    'Sodium, potassium, magnesium, citric acid, stevia',
  ],
  prices: [
    8.49, 6.49, 3.49, 9.99, 3.49, 2.79, 5.49, 6.49, 5.49, 18.99, 3.99, 4.79, 3.89, 8.49, 12.99, 14.99, 5.49, 7.99, 8.99, 4.49,
    6.99, 9.99, 5.99, 11.99, 4.99, 7.49, 3.29, 8.99,
  ],
};
