/** 28 home & office products — photo pool slice [28..55]. */
export default {
  names: [
    'Recycled Glass Vase',
    'FSC Wood Side Table',
    'Natural Fiber Rug',
    'Low Energy LED Lamp',
    'Reusable Storage Jars',
    'Organic Cotton Throw',
    'Upcycled Decor Basket',
    'Recycled Notebook Pack',
    'Bamboo Desk Organizer',
    'Refillable Pen Set',
    'Cork Mouse Pad',
    'Eco Sticky Notes',
    'FSC Paper Planner',
    'Reusable Cable Ties',
    'Hemp Cushion Cover Set',
    'Wool Dryer Balls',
    'Bamboo Coaster Set',
    'Glass Infuser Teapot',
    'Linen Napkin Quartet',
    'Beeswax Pillar Candle',
    'Terracotta Planter Pair',
    'Rattan Laundry Hamper',
    'Cork Bulletin Tiles',
    'Recycled Wool Throw',
    'Soy Wax Melts Tin',
    'Jute Entry Mat',
    'Stainless Bento Lunch Box',
    'Ceramic Salt Cellar Duo',
  ],
  descriptions: [
    'Hand-blown vase from recycled glass with a soft green tint.',
    'Side table in FSC-certified solid wood with low-VOC finish.',
    'Area rug in undyed jute and wool for living spaces.',
    'LED lamp with warm dimming and recycled aluminum heat sink.',
    'Glass storage jars with bamboo lids for pantry staples.',
    'Throw blanket woven from GOTS organic cotton.',
    'Decor basket upcycled from textile offcuts and cotton rope.',
    'Notebook trio with recycled-card covers and dot-grid pages.',
    'Bamboo desk organizer with trays for pens and accessories.',
    'Refillable pen set with compostable ink cartridges.',
    'Cork desk mat sized for mouse and compact keyboard.',
    'Sticky notes made from sugarcane paper with gentle adhesive.',
    'Weekly planner on FSC paper with lay-flat binding.',
    'Reusable cable ties for laptop and charger cords.',
    'Two cushion covers in heavy hemp blend with hidden zippers.',
    'Set of six wool dryer balls to soften laundry without sheets.',
    'Round coasters in laminated bamboo with cork backing.',
    'Borosilicate teapot with stainless infuser and bamboo handle.',
    'Four hemstitched napkins in stone-washed linen.',
    'Pillar candle with cotton wick in recycled glass holder.',
    'Two unglazed terracotta pots with drainage saucers.',
    'Hand-woven rattan hamper with cotton liner and lid.',
    'Six cork tiles for pinning notes; adhesive squares included.',
    'Throw in recycled wool with fringed edges.',
    'Tin of soy wax melts with botanical essential oils.',
    'Dense jute mat with latex backing for doorways.',
    'Leak-proof stainless bento with bamboo lid and divider.',
    'Two small ceramic cellars for salt and pepper.',
  ],
  materials: [
    'Recycled glass',
    'FSC-certified solid hardwood, low-VOC finish',
    'Jute, undyed wool',
    'LED module, recycled aluminum, steel base',
    'Borosilicate glass, bamboo lid',
    'GOTS organic cotton',
    'Recycled cotton rope, pine frame',
    'Recycled paper, kraft cover',
    'Bamboo ply, steel hardware',
    'Recycled plastic barrel, plant-based ink',
    'Natural cork',
    'Sugarcane paper, low-tack adhesive',
    'FSC paper, linen thread',
    'Recycled PET hook-and-loop, elastic',
    'Hemp, organic cotton',
    'New Zealand wool',
    'Moso bamboo, cork',
    'Borosilicate glass, stainless steel',
    'European linen',
    'Soy wax, cotton wick, glass',
    'Terracotta clay',
    'Rattan, cotton liner',
    'Natural cork, adhesive',
    'Recycled wool, acrylic blend',
    'Soy wax, essential oils, tin',
    'Jute, natural rubber backing',
    '18/8 stainless steel, bamboo',
    'Stoneware ceramic',
  ],
  prices: [
    22.99, 72.99, 54.99, 28.99, 16.99, 34.99, 26.99, 11.99, 18.99, 14.49, 9.99, 6.49, 12.99, 7.49, 24.99, 18.99, 12.99,
    36.99, 21.99, 14.99, 19.99, 44.99, 16.99, 48.99, 11.49, 32.99, 28.99, 15.99,
  ],
};
