export default {
  names: [
    'Organic Baby Onesie',
    'Natural Rubber Teether',
    'Bamboo Kids Plate Set',
    'Eco Story Book Set',
    'Reusable Snack Pouch',
    'Wooden Learning Blocks',
    'Organic Cotton Blanket',
    'Muslin Burp Cloths',
    'Wheat Straw Sippy Cup',
    'Crayon Rock Set',
    'Balance Bike Wood',
    'Sun Hat Organic',
    'Bath Toy Boats',
    'Night Light Owl',
    'Puzzle Floor Farm',
    'Stroller Organizer Hemp',
    'Wool Booties',
    'Silicone Bib Pocket',
    'Growth Chart Canvas',
    'Plush Bunny Recycled',
    'Snack Container Steel',
    'Finger Paint Powder',
    'Crib Fitted Sheet',
    'Backpack Mini',
    'Bubble Wand Wood',
    'Sound Book Nature',
    'Training Chopsticks',
    'Sunscreen Baby Stick',
  ],
  descriptions: [
    'Organic cotton onesie with snap shoulders for easy changes.',
    'Teething ring molded from natural rubber without BPA.',
    'Bamboo kids plate and cup set with divided sections.',
    'Storybook set printed on FSC paper with soy inks.',
    'Silicone snack pouch for purees and finger foods.',
    'Wooden blocks with water-based paints for toddlers.',
    'Muslin swaddle blanket in breathable organic cotton.',
    'Three-layer burp cloths with snap for shoulder.',
    'Sippy cup with wheat-straw composite and silicone spout.',
    'Chunky rock-shaped crayons easy for small hands.',
    'No-pedal balance bike from birch plywood.',
    'Wide-brim hat with chin strap; UPF rated fabric.',
    'Three floating boats in natural rubber.',
    'LED owl with warm dimmer and timer.',
    'Large foam puzzle pieces with farm animals.',
    'Stroller caddy in hemp canvas with cup holders.',
    'Infant booties in merino wool blend.',
    'Wide pocket catches spills; rolls for travel.',
    'Canvas chart with non-toxic ink markers.',
    'Soft toy stuffed with recycled PET fiber.',
    'Insulated snack jar keeps food warm or cold.',
    'Mix-with-water finger paints from plant pigments.',
    'Fitted sheet in jersey knit organic cotton.',
    'Mini backpack with chest clip and reflective trim.',
    'Bubble solution in paper bottle; wood wand.',
    'Sound buttons with bird and forest recordings.',
    'Silicone helper attaches to regular chopsticks.',
    'Mineral SPF in push-up paper tube for babies.',
  ],
  materials: [
    'GOTS organic cotton',
    'Hevea natural rubber',
    'Bamboo fiber, plant-based lacquer',
    'FSC paper, soy ink',
    'Platinum silicone',
    'Beech wood, water-based paint',
    'Organic cotton muslin',
    'Organic cotton, bamboo rayon',
    'Wheat straw composite, silicone',
    'Natural wax pigments, soy',
    'Birch plywood, rubber tires',
    'Organic cotton canvas',
    'Natural rubber',
    'ABS, LED, recycled plastic base',
    'EVA foam, soy ink print',
    'Hemp canvas, recycled polyester lining',
    'Merino wool, elastane',
    'Platinum silicone',
    'Organic cotton canvas',
    'Recycled PET plush, organic cotton shell',
    '18/8 stainless steel',
    'Corn starch, mineral pigments',
    'GOTS organic cotton jersey',
    'Recycled PET, nylon straps',
    'Beech wood, castile soap base',
    'FSC board, soy ink, electronics',
    'Silicone, BPA-free',
    'Zinc oxide, coconut oil, beeswax',
  ],
  prices: [
    14.99, 8.99, 17.99, 11.99, 9.99, 22.99, 26.99, 16.99, 12.49, 9.99, 79.99, 18.99, 14.99, 24.99, 19.99, 21.99, 22.99,
    11.99, 27.99, 19.99, 16.99, 12.99, 28.99, 32.99, 7.99, 15.99, 8.49, 14.49,
  ],
};
