/** 28 kitchen — photo pool [84..111]. */
export default {
  names: [
    'Stainless Steel Straw Set',
    'Bamboo Cooking Utensils',
    'Reusable Silicone Food Bags',
    'Compost Bin Caddy',
    'Glass Meal Prep Containers',
    'Cotton Produce Bags',
    'Beeswax Food Wrap Kit',
    'Cast Iron Skillet',
    'Cork Trivet Set',
    'Glass Oil Cruet',
    'Hemp Apron',
    'Stainless Pasta Measure',
    'Silicone Baking Mat',
    'Ceramic Mortar Pestle',
    'Wooden Salad Servers',
    'Tea Infuser Basket',
    'Compostable Sponge Pack',
    'Bamboo Cutting Board',
    'Glass Spice Jars',
    'Silicone Lids Universal',
    'Linen Bread Bag',
    'Steel Ice Cube Tray',
    'Coconut Bowl Set',
    'Reusable Bowl Covers',
    'Stovetop Kettle',
    'Cotton Dish Cloths',
    'Fermentation Jar Kit',
    'Wooden Dish Brush',
  ],
  descriptions: [
    'Set of metal straws plus a slender cleaning brush and pouch.',
    'Five-piece bamboo utensil set for cooking and serving.',
    'Leak-proof silicone bags for freezer, lunch, and sous-vide.',
    'Countertop compost caddy with replaceable charcoal filter.',
    'Glass meal-prep containers with snap lids for leftovers.',
    'GOTS organic cotton mesh bags for produce runs.',
    'Reusable food wraps using beeswax on organic cotton.',
    'Pre-seasoned cast iron skillet sized for daily cooking.',
    'Three cork trivets that protect counters from hot pans.',
    'Borosilicate cruet with pourer for oils and vinegars.',
    'Adjustable neck apron in heavy hemp with pockets.',
    'Portion rings for spaghetti in brushed stainless.',
    'Half-sheet silicone mat; oven safe to high heat.',
    'Stone mortar with pestle for spices and pastes.',
    'Pair of carved wood servers for greens.',
    'Fine mesh basket for loose leaf in mugs or pots.',
    'Plant-fiber sponges; compost when worn.',
    'Reversible board with juice groove.',
    'Six square jars with shaker lids and chalk labels.',
    'Stretch lids for bowls and cans in multiple sizes.',
    'Drawstring bag keeps bread crusty longer.',
    'Metal tray makes large slow-melting cubes.',
    'Two polished coconut shells for smoothie bowls.',
    'Cotton covers with elastic for leftovers.',
    'Enamel-coated steel kettle for gas and electric.',
    'Pack of waffle-weave cloths for drying dishes.',
    'Wide-mouth jar with airlock for kraut and kimchi.',
    'Tampico bristles on beech handle for pots.',
  ],
  materials: [
    '18/8 stainless steel, nylon brush',
    'Moso bamboo, food-grade oil',
    'Platinum silicone, BPA-free',
    'Recycled plastic, activated charcoal filter',
    'Tempered glass, polypropylene lid',
    'GOTS organic cotton mesh',
    'Organic cotton, beeswax, tree resin',
    'Cast iron, vegetable oil seasoning',
    'Agglomerated cork',
    'Borosilicate glass, stainless pourer',
    'Hemp canvas, cotton straps',
    'Stainless steel',
    'Silicone embedded with fiberglass',
    'Granite stone, wood pestle',
    'Olive wood',
    'Stainless steel mesh, silicone handle',
    'Cellulose, plant fiber',
    'Bamboo, mineral oil finish',
    'Soda-lime glass, stainless cap',
    'Platinum silicone',
    'Organic cotton, beeswax lining',
    'Stainless steel',
    'Coconut shell, plant lacquer',
    'Organic cotton, elastic',
    'Enameled steel, beech handle',
    'Organic cotton',
    'Glass, silicone airlock, steel spring',
    'Beech wood, tampico fiber',
  ],
  prices: [
    7.49, 14.99, 17.99, 22.99, 18.99, 9.99, 14.99, 42.99, 16.99, 12.99, 24.99, 8.99, 11.99, 28.99, 14.49, 9.99, 7.99,
    32.99, 19.99, 13.99, 11.49, 14.99, 22.99, 17.99, 39.99, 12.99, 26.99, 8.49,
  ],
};
