/** 28 garden & outdoors — photo pool [140..167]. */
export default {
  names: [
    'Recycled Trail Backpack',
    'Insulated Steel Bottle',
    'Solar Camp Lantern',
    'Reusable Travel Cutlery',
    'Eco Picnic Blanket',
    'Cork Yoga Mat',
    'Compostable Wet Wipes',
    'Compost Starter Kit',
    'Biodegradable Seed Pots',
    'Reclaimed Wood Planter',
    'Rainwater Collection Barrel',
    'Organic Herb Grow Set',
    'Natural Coir Mulch Mat',
    'Bamboo Plant Labels',
    'Hiking Pole Pair',
    'Recycled Fleece Beanie',
    'Packable Hammock',
    'Solar String Lights',
    'Collapsible Silicone Bowl',
    'Trail Gaiters',
    'Waxed Canvas Tarp',
    'Fire Starter Cubes',
    'Portable Water Filter',
    'Recycled Rope Dog Leash',
    'Bird Feeder Cedar',
    'Stacking Rain Barrel Kit',
    'Foldable Camp Stool',
    'Organic Potting Soil Bag',
  ],
  descriptions: [
    'Daypack with recycled ripstop shell and breathable harness.',
    'Insulated steel bottle that keeps drinks cold or hot for hours.',
    'Rechargeable camp lantern with dimmable warm LED.',
    'Travel cutlery set in a roll: knife, fork, spoon, chopsticks.',
    'Picnic blanket with recycled-fiber backing and cotton top.',
    'Cork and natural rubber yoga mat for studio or trail.',
    'Plant-based wet wipes for quick cleanup; compost where accepted.',
    'Compost starter mix with brown and green balance tips.',
    'Biodegradable seedling pots that break down in garden soil.',
    'Planter box from reclaimed wood with drainage tray.',
    'Rain barrel kit with food-grade liner and diverter.',
    'Herb growing kit with organic soil discs and seed sachets.',
    'Coir mulch mat to hold moisture and block weeds.',
    'Bamboo plant labels you can write on for rows and beds.',
    'Lightweight aluminum poles with cork grips.',
    'Warm beanie in recycled PET fleece.',
    'Tree-friendly straps and stuff sack included.',
    'Warm-white LEDs on copper wire; solar charged.',
    '1.2 L bowl folds flat for backpacking meals.',
    'Ankle gaiters keep debris out of boots.',
    'Treated canvas tarp for shelter or ground cover.',
    'Sawdust and wax cubes for damp wood.',
    'Squeeze filter rated for trail bacteria.',
    'Climbing rope construction with locking carabiner.',
    'Cedar feeder with plexi windows.',
    'Modular barrels link for more capacity.',
    'Alloy frame with recycled PET seat.',
    'OMRI-listed blend for containers and beds.',
  ],
  materials: [
    'Recycled polyester ripstop, nylon webbing',
    '18/8 stainless steel, polypropylene lid',
    'ABS housing, lithium cell, LED',
    'Stainless steel, bamboo, cotton roll',
    'Recycled PET fleece, organic cotton',
    'Natural cork, natural rubber',
    'Wood pulp viscose, aloe extract',
    'Coconut coir, alfalfa meal, gypsum',
    'Recycled paper pulp, natural latex binder',
    'Reclaimed pine, natural oil finish',
    'Recycled HDPE, brass hardware',
    'Organic coir, non-GMO seeds',
    'Natural coconut coir fiber',
    'Moso bamboo',
    '7075 aluminum, cork',
    'Recycled polyester fleece',
    'Parachute nylon, polyester strap',
    'Monocrystalline panel, copper wire',
    'Platinum silicone, nylon rim',
    'Recycled polyester, elastic',
    'Cotton canvas, beeswax',
    'Wood fiber, natural wax',
    'Hollow-fiber membrane, BPA-free housing',
    'Recycled climbing rope, aluminum',
    'Western red cedar, acrylic',
    'Recycled PE barrel, brass spigot',
    'Aluminum alloy, recycled fabric',
    'Peat-free compost, coco coir, perlite',
  ],
  prices: [
    44.99, 21.99, 24.99, 15.99, 32.99, 29.99, 6.99, 12.99, 9.99, 49.99, 69.99, 16.99, 11.99, 8.99, 54.99, 18.99, 42.99,
    34.99, 14.49, 22.99, 59.99, 8.99, 39.99, 24.99, 28.99, 89.99, 19.99, 12.49,
  ],
};
