export default {
  names: [
    'Natural Toothpaste Tabs',
    'Compostable Floss Kit',
    'Refillable Hand Wash',
    'Plant-Based Face Cleanser',
    'Bamboo Toothbrush Set',
    'Eco Body Lotion',
    'Solid Conditioner Bar',
    'Aluminum Safety Razor',
    'Konjac Sponge Duo',
    'Shea Lip Balm Tin',
    'Dry Shampoo Powder',
    'Reusable Cotton Swabs',
    'Mineral Deodorant Stick',
    'Aloe Shaving Cream',
    'Glass Pump Dispenser',
    'Pumice Stone Brush',
    'Tea Tree Foot Spray',
    'Rosehip Facial Oil',
    'Charcoal Dental Powder',
    'Silk Dental Tape',
    'Oat Hand Cream',
    'Bamboo Cotton Buds',
    'Citrus Shower Steamers',
    'SPF Lip Shield',
    'Lavender Pillow Mist',
    'Cornstarch Body Powder',
    'Peppermint Mouthwash Tabs',
    'Biodegradable Bandage Roll',
  ],
  descriptions: [
    'Fluoride-free toothpaste tablets with peppermint polish.',
    'Compostable floss on a refillable glass spool.',
    'Concentrated hand wash; mix with water in a reusable dispenser.',
    'Gentle face cleanser with aloe and coconut-derived surfactants.',
    'Bamboo toothbrush set with soft plant-based bristles.',
    'Body lotion with shea butter and fast-absorbing plant oils.',
    'Solid conditioner bar to skip plastic bottles in the shower.',
    'Weighted safety razor with replaceable steel blades.',
    'Two konjac sponges for gentle daily exfoliation.',
    'Rich lip balm in a sliding tin; unscented option.',
    'Talc-free powder refreshes hair between washes.',
    'Silicone-tipped swabs you wash and reuse.',
    'Baking soda and mineral stick with push-up paper tube.',
    'Brushless cream with aloe for wet shaving.',
    'Empty amber glass bottle fits standard pumps.',
    'Natural pumice on bamboo handle for heels.',
    'Cooling spray with tea tree and witch hazel.',
    'Cold-pressed rosehip oil for evening routine.',
    'Activated charcoal polish for weekly whitening.',
    'Silk floss in a refillable metal dispenser.',
    'Rich oat and calendula cream for dry hands.',
    'Cotton buds on bamboo sticks in recycled box.',
    'Fizzing tablets with essential oils for spa showers.',
    'Mineral SPF lip balm in paper tube.',
    'Linen spray with lavender for pillows and linens.',
    'Absorbent powder with chamomile; talc-free.',
    'Mouthwash tablets dissolve in water in a jar.',
    'Flexible fabric bandage on a compostable spool.',
  ],
  materials: [
    'Sorbitol, calcium carbonate, peppermint oil',
    'Corn PLA filament, candelilla wax, glass spool',
    'Coconut-derived surfactants, glycerin, essential oils',
    'Aloe juice, chamomile extract, mild surfactants',
    'Bamboo, castor-oil based bristles',
    'Shea butter, sunflower oil, vitamin E',
    'Coconut oil, BTMS, essential oils',
    'Brass alloy, steel blades',
    'Konjac root fiber',
    'Shea butter, beeswax, vitamin E',
    'Arrowroot, kaolin clay, cocoa powder',
    'Medical-grade silicone, stainless case',
    'Coconut oil, magnesium, essential oils',
    'Aloe, glycerin, plant stearic acid',
    'Soda-lime glass',
    'Pumice stone, bamboo',
    'Witch hazel, tea tree oil, water',
    'Rosa canina seed oil',
    'Charcoal, bentonite clay, mint oil',
    'Peace silk, stainless steel case',
    'Oat kernel oil, shea butter',
    'Organic cotton, bamboo stem',
    'Citric acid, baking soda, oils',
    'Zinc oxide, coconut oil, beeswax',
    'Lavender hydrosol, alcohol from grain',
    'Cornstarch, kaolin, chamomile',
    'Sodium bicarbonate, xylitol, oils',
    'Bamboo fiber, natural latex adhesive',
  ],
  prices: [
    8.49, 6.99, 9.99, 11.99, 8.99, 13.99, 8.49, 24.99, 9.49, 7.99, 14.99, 12.99, 10.99, 11.49, 8.99, 6.99, 9.99, 18.99,
    11.99, 7.49, 12.49, 5.99, 13.49, 8.99, 10.49, 9.99, 7.99, 6.49,
  ],
};
