export default {
  names: [
    'Recycled Phone Case',
    'Solar Power Bank',
    'Bamboo Keyboard Wrist Rest',
    'Eco Cable Organizer',
    'Bioplastic Earbud Case',
    'Energy Saving Smart Plug',
    'Recycled Laptop Sleeve',
    'USB-C Charging Cable Braided',
    'Webcam Privacy Slider',
    'Desk Lamp LED Wooden',
    'Bluetooth Speaker Hemp',
    'Wireless Mouse Recycled',
    'Tablet Stand Bamboo',
    'Screen Cleaning Kit Plant',
    'Portable SSD Enclosure',
    'Laptop Stand Aluminum',
    'USB Hub Powered',
    'Monitor Riser Cork',
    'Phone Tripod Mini',
    'RFID Blocking Card Sleeve',
    'Stylus Pen Bamboo',
    'Over-Ear Headphones Repair Kit',
    'Cable Label Set',
    'Surge Protector Strip',
    'Webcam 1080p Clip',
    'Mouse Pad Cork',
    'Travel Adapter Universal',
    'Battery Recycling Mailer',
  ],
  descriptions: [
    'Phone case molded from recycled handset plastics where noted.',
    'Solar-assisted power bank for phones on multi-day trips.',
    'Keyboard wrist rest with laminated bamboo and cork base.',
    'Cable organizer kit with silicone ties and printed labels.',
    'Earbud case in a bio-based polymer shell.',
    'Smart plug with scheduling to trim standby energy use.',
    'Laptop sleeve with recycled nylon shell and fleece lining.',
    'Braided sleeve from recycled PET; supports fast charge.',
    'Stick-on slider covers laptop camera when not in use.',
    'Warm LED desk lamp with solid wood base and dimmer.',
    'Compact speaker with hemp fabric grill and recycled housing.',
    'Ergonomic mouse with shell from recycled ABS.',
    'Foldable stand for tablets up to eleven inches.',
    'Spray and cloth safe for coated screens; refillable bottle.',
    'Aluminum enclosure for NVMe drives; tool-free latch.',
    'Raises laptop eye level; ventilated for cooling.',
    'Four USB-A ports with BC charging and LED indicator.',
    'Elevates monitor with storage nook; cork feet.',
    'Flexible legs wrap around poles or stand on desk.',
    'Slim sleeve blocks RFID skimming in wallet.',
    'Passive stylus with bamboo barrel for touch screens.',
    'Screws, pads, and headband parts to extend headphone life.',
    'Color-coded labels for home and office cable runs.',
    'Seven outlets with master switch and joule protection.',
    'Autofocus HD webcam with privacy shutter.',
    'Natural cork surface with nonslip backing.',
    'Type-C and USB-A ports for EU UK US plugs.',
    'Prepaid mailer recycles small batteries responsibly.',
  ],
  materials: [
    'Recycled polycarbonate blend',
    'Lithium cells, monocrystalline solar strip',
    'Bamboo laminate, cork',
    'Silicone, recycled PET tags',
    'Bio-based polymer',
    'Fire-rated ABS, Wi-Fi radio',
    'Recycled nylon, recycled polyester fleece',
    'Recycled PET braid, copper conductors',
    'ABS, adhesive pad',
    'Solid ash, LED module, steel',
    'Hemp fabric, recycled plastic housing',
    'Recycled ABS, PTFE feet',
    'Bamboo ply, steel hinge',
    'Plant surfactants, microfiber, glass bottle',
    'Aluminum, USB 3.2 controller',
    'Recycled aluminum, silicone pads',
    'ABS, copper ports, steel housing',
    'Cork, steel frame',
    'ABS, silicone, rubber feet',
    'Recycled PET, copper mesh',
    'Bamboo, conductive rubber tip',
    'Steel screws, protein leather pads',
    'Recycled paper, soy ink',
    'Steel, MOV, copper busbar',
    'Glass lens, ABS, CMOS sensor',
    'Natural cork, recycled rubber',
    'Polycarbonate, brass pins',
    'Cardboard, prepaid postage',
  ],
  prices: [
    16.99, 28.99, 16.99, 11.99, 14.99, 17.99, 32.99, 12.99, 8.99, 42.99, 34.99, 24.99, 18.99, 9.99, 36.99, 45.99, 22.99, 38.99,
    14.49, 11.99, 12.99, 8.99, 6.99, 29.99, 49.99, 16.99, 24.99, 7.99,
  ],
};
